server:
  port: 80
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8
    username: icdpub
    password: Sdkf123#
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
  aop:
    auto: true
#  activemq:
#    broker-url: tcp://127.0.0.1:61616
#    in-memory: false
#    pool:
#      enabled: true
#      max-connections: 5
#      idle-timeout: 30000
#      expiry-timeout: 0
#  jms:
#    pub-sub-domain: true

#mybatis
mybatis:
  # 实体类扫描
  type-aliases-package: com.all.bnmg.entity
  # 配置映射文件位置
  mapper-locations: classpath:mapper/*.xml
  # 开启驼峰匹配
  mapUnderscoreToCamelCase: true
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
######################### Druid连接池的配置信息  #################
spring.druid.initialSize: 5                                 #初始化连接大小
spring.druid.minIdle: 5                                     #最小连接池数量
spring.druid.maxActive: 20                                  #最大连接池数量
spring.druid.maxWait: 60000                                 #获取连接时最大等待时间，单位毫秒
spring.druid.timeBetweenEvictionRunsMillis: 60000           #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.druid.minEvictableIdleTimeMillis: 300000             #配置一个连接在池中最小生存的时间，单位是毫秒
spring.druid.validationQuery: SELECT 1 FROM DUAL            #测试连接
spring.druid.testWhileIdle: true                            #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
spring.druid.testOnBorrow: false                            #获取连接时执行检测，建议关闭，影响性能
spring.druid.testOnReturn: false                            #归还连接时执行检测，建议关闭，影响性能
spring.druid.poolPreparedStatements: false                  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
spring.druid.maxPoolPreparedStatementPerConnectionSize: 20  #开启poolPreparedStatements后生效
spring.druid.filters: stat,wall,log4j                       #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
spring.druid.connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
logging.level.root: info
logging.level.com.all.bnmg.dao: debug
logging.level.org.springframework.web: debug
logging.level.org.apache.tomcat: warn
