package com.all.bnmg.dao;

import com.all.bnmg.entity.TSysDepartment;
import com.all.bnmg.entity.TreeNode;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface TSysDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_department
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_department
     *
     * @mbg.generated
     */
    int insert(TSysDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_department
     *
     * @mbg.generated
     */
    TSysDepartment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_department
     *
     * @mbg.generated
     */
    List<TSysDepartment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSysDepartment record);

    TSysDepartment selectByCode(String code);
    /**
     * 根据父节点获取所有子节点
     * */
    List<TreeNode> selectByPcode(String pcode);
}